// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3OhQd6K91289MZdikUtC9W2K9ZQGuwtI',
    appId: '1:713658619973:web:06cf6b1badb22a2ff7ab2c',
    messagingSenderId: '713658619973',
    projectId: 'demoapp-854e2',
    authDomain: 'demoapp-854e2.firebaseapp.com',
    storageBucket: 'demoapp-854e2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBSy8phdbphEg5Qtkw1WdHVnoLTrC_004',
    appId: '1:713658619973:android:6b1e31180bb409fbf7ab2c',
    messagingSenderId: '713658619973',
    projectId: 'demoapp-854e2',
    storageBucket: 'demoapp-854e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFdfrul46Bdyqd5Ne9T-QWmQXNya4XhSM',
    appId: '1:713658619973:ios:7341df6f685592d5f7ab2c',
    messagingSenderId: '713658619973',
    projectId: 'demoapp-854e2',
    storageBucket: 'demoapp-854e2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp349',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFdfrul46Bdyqd5Ne9T-QWmQXNya4XhSM',
    appId: '1:713658619973:ios:7341df6f685592d5f7ab2c',
    messagingSenderId: '713658619973',
    projectId: 'demoapp-854e2',
    storageBucket: 'demoapp-854e2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp349',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3OhQd6K91289MZdikUtC9W2K9ZQGuwtI',
    appId: '1:713658619973:web:f2430b10e4794a7bf7ab2c',
    messagingSenderId: '713658619973',
    projectId: 'demoapp-854e2',
    authDomain: 'demoapp-854e2.firebaseapp.com',
    storageBucket: 'demoapp-854e2.firebasestorage.app',
  );
}
